Removed Postgres 13 from RELATED_IMAGE.
CrunchyData/postgres-operator-examples pull request #191
Opened 2023-03-14 21:16 UTC by ValClarkson

Removed Postgres 13 from RELATED_IMAGE.  Now that we've had 2 patch releases of Postgres 15 we are dropping postgres 13.

Issue [sc-17907]

2023-03-20 19:37 UTC, tjmoore4 reviewed
:thinking: Would we want to update our image override [example](https://github.com/CrunchyData/postgres-operator-examples/blob/main/helm/postgres/values.yaml#L50) as well?

2023-03-22 19:06 UTC, tjmoore4 requested changes

2023-03-22 20:42 UTC, ValClarkson commented on helm/postgres/values.yaml
> +# imagePgBackRest: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.44-4
yup that is a typo thanks for the catch! I'll get that fixed

2023-03-22 20:48 UTC, tjmoore4 approved these changes

2023-03-22 21:19 UTC, merged